concat_channels_dim: 700
dmel_groups: 100

model:
  encoder:
    input_channels: 10
    residual_channels: 70

  vocoder:
    ckpt_path: null
    h_path: null

callbacks:
  model_checkpoint:
    dirpath: /data0/questar/users/wuzhiyue/ckpt
    filename: '{epoch:03d}-{step:06d}_20hz'

tensorboard_logger:
  save_dir: /home/wuzhiyue/CodecLLM-master/dmel_codec/tb_logs
  name: dmel_codec_20hz

# if more parameters are needed, add them here: 